version: 1
builder:
  configs:
  - platform: ios
    scheme: SpeechManager
  - platform: macos-xcodebuild
    scheme: SpeechManager
  - platform: tvos
    scheme: SpeechManager
  - platform: watchos
    scheme: SpeechManager
  - documentation_targets: [SpeechManager]
